baseURL = 'http://mrhota.github.io/misterajazz'
languageCode = 'en-us'
title = 'Mr. A Jazz'
theme = 'hugo-coder'

paginate = 20

[markup.highlight]
style = "github-dark"
[markup.goldmark.renderer]
unsafe = true

[params]
  author = "AJ Gardner"
  info = ""
  description = "AJ Gardner's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  #faviconSVG = "/img/favicon.svg"
  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mrhota/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/nmodprime/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Interests"
  weight = 3
  url = "interests/"
[[menu.main]]
  name = "Projects"
  weight = 4
  url = "projects/"
[[menu.main]]
  name = "Alphabet Superset"
  weight = 5
  url = "weeklies/"
